ci: 👷 🎡 add install script

diff --git a/stub/.husky/prepare-commit-msg b/stub/.husky/prepare-commit-msg
--- a/stub/.husky/prepare-commit-msg
+++ b/stub/.husky/prepare-commit-msg
@@ -9,7 +9,7 @@ fi
 
 # Edit commit message
 if [ $(grep -cv -e '^#' -e '^$' .git/COMMIT_EDITMSG) -eq 0 ]; then
-  (exec </dev/tty && npx git-cz -e --hook || echo -e "\e[1m\e[31m!\e[0m Unable to start commitizen.") || echo -e "\e[1m\e[31m!\e[0m Commitizen failed."
+  (exec </dev/tty && npx cz --hook || echo -e "\e[1m\e[31m!\e[0m Unable to start commitizen.") || echo -e "\e[1m\e[31m!\e[0m Commitizen failed."
 else
   echo -e "\e[34m→\e[0m Commitizen not relevant. Skipping..."
 fi
