Improve scripts & ide config

diff --git a/.husky/prepare-commit-msg b/.husky/prepare-commit-msg
--- a/.husky/prepare-commit-msg
+++ b/.husky/prepare-commit-msg
@@ -2,7 +2,12 @@
 export PATH=/usr/bin:$PATH
 . "$(dirname "$0")/_/husky.sh"
 
-if [ $(grep -cv -e '^#' -e '^$' .git/COMMIT_EDITMSG) -eq 0 ]
-then
-  (exec < /dev/tty && echo "$TERM" && npx git-cz -e --hook || echo skip commit) || echo skip prepare
+# Enable colors in Powershell
+exec >/dev/tty 2>&1
+
+# Edit commit message
+if [ $(grep -cv -e '^#' -e '^$' .git/COMMIT_EDITMSG) -eq 0 ]; then
+  (exec </dev/tty && npx git-cz -e --hook || echo -e "\e[1m\e[31m!\e[0m Unable to start commitizen.") || echo -e "\e[1m\e[31m!\e[0m Commitizen failed."
+else
+  echo -e "\e[34m→\e[0m Commitizen not relevant. Skipping..."
 fi
